name=LTR507ALSOpticalSensor
version=0.0.0
author=mumanchu
maintainer=mumanchu <info@muman.ch>
sentence=Arduino Library for LTR-507ALS Optical Sensor
paragraph=With I2C interface
category=Sensors
includes=LTR507ALSOpticalSensor.h
url=https://github.com/mumanchu/LTR507ALSOpticalSensor
architectures=*
